// Code generated by internal/generators/errcodegen/main.go; DO NOT EDIT.
package twilio

func GetErrorMessage(code int) string {
	switch code {

	case 400:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Bad Request"

	case 403:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Forbidden"

	case 404:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Not Found"

	case 410:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Unknown Error Code"

	case 503:
		// LogLevel: ERROR
		// LogType: TWILIO
		return "Internal Error"

	case 10001:
		// LogLevel: ERROR
		// LogType: TWILIO
		return "Account is not active"

	case 10003:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Incoming call rejected due to inactive account"

	case 10004:
		// LogLevel: ERROR
		// LogType: TWILIO
		return "Call concurrency limit exceeded"

	case 11200:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "HTTP retrieval failure"

	case 11205:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "HTTP connection failure"

	case 11210:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "HTTP bad host name"

	case 11216:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "HTTP invalid redirect"

	case 11217:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "HTTP error response code"

	case 11220:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "SSL/TLS Handshake Error"

	case 11240:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "HTTP connection edge location is invalid"

	case 11241:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "HTTP connection edge location is not supported"

	case 12300:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid Content-Type"

	case 13224:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Dial: Twilio does not support calling this number or the number is invalid"

	case 13299:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "2010 Conference API feature requested using 2008 API"

	case 19003:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Contact with the unique_customer_provided_id provided already exists"

	case 19004:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid or missing Contact input"

	case 19005:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Contact validation error"

	case 19010:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid contact search request"

	case 19011:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "When updating a contact, invalid JSON syntax or invalid field that cannot be updated by this endpoint"

	case 19012:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "When updating a contact at least one field should be updated"

	case 19013:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "At least one of the following fields is required for a contact: first_name, middle_name, last_name, legal_name, preferred_name, unique_customer_provided_id or channel"

	case 19014:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Can fetch contact either by unique_customer_provided_id or channel "

	case 19020:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Contact with the provided channel value already exists"

	case 19021:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Only one channel can be set as primary"

	case 19022:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid channel"

	case 19023:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid channel type"

	case 19024:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid channel input"

	case 19025:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Channel validation error"

	case 19026:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Maximum number of channels allowed reached"

	case 19027:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid Channel Description"

	case 19028:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Channel value can not be updated"

	case 19029:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "When updating a channel at least one field should be updated"

	case 19030:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid location type"

	case 19031:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Maximum number of locations allowed reached "

	case 19032:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid location input"

	case 19033:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Location validation error"

	case 19034:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid country code"

	case 19035:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid page size, it must be between 1 and 25 if specified"

	case 19036:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid page token"

	case 19037:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "When updating a location at least one field should be updated"

	case 19040:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Custom Field provided is not defined"

	case 19041:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid or missing Custom Field input"

	case 19042:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Custom Field validation error"

	case 19050:
		// LogLevel: ERROR
		// LogType: TWILIO
		return "Internal Server Error"

	case 20003:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Permission Denied"

	case 20009:
		// LogLevel: ERROR
		// LogType: TWILIO
		return "Cannot delete this resource before it is complete"

	case 20012:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid TLSv1.2 Cipher Suite"

	case 20020:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "No update/state change is observed for the data entered"

	case 20021:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Phone number rejected by T-Mobile SDG Service Provisioning API"

	case 20023:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Phone number is not correct: it cannot be null or have non-decimal symbols"

	case 20429:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Too Many Requests"

	case 21210:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "'From' phone number not verified"

	case 21211:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid 'To' Phone Number"

	case 21212:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid 'From' Number"

	case 21235:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "IP Access Control List Validation Error"

	case 21236:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "IP Access Control List Dependencies Violation"

	case 21237:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Maximum IP Addresses Reached for List"

	case 21238:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Address Validation Error"

	case 21239:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Maximum Credential Lists Reached"

	case 21240:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Credential List Validation Error"

	case 21241:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Credential List Dependencies Violation"

	case 21242:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Maximum Credentials Reached for List"

	case 21243:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Credential Validation Error"

	case 21255:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Maximum IP Access Control Lists reached"

	case 21264:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "'From' phone number not verified"

	case 21401:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid Phone Number"

	case 21421:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Phone Number is invalid"

	case 21602:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Message body is required"

	case 21604:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "The destination 'To' phone number is required to send an SMS"

	case 21617:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "The concatenated message body exceeds the 1600 character limit"

	case 21620:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid media URL(s)"

	case 21621:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "The 'From' number has not been enabled for MMS"

	case 21653:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "There are more recipient addresses than allowed"

	case 21701:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "The Messaging Service does not exist"

	case 21705:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "The Messaging Service is invalid"

	case 21900:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "DltPEId is invalid"

	case 21901:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "DltTemplateId is invalid"

	case 22223:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Regulatory Bundle is not eligible to be Copied"

	case 30112:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Account is not found"

	case 32016:
		// LogLevel: ERROR
		// LogType: CARRIER
		return "PSTN PDD timeout"

	case 32017:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "PSTN: Carrier blocked call due to calling number (caller ID)"

	case 32209:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "SIP: Secure transport required"

	case 32216:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "SIP: SIP Address is on a deny list"

	case 50353:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Conversation with provided unique name already exists"

	case 51007:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Client Connection: Token authentication is rejected"

	case 52004:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Credential SID not specified"

	case 60001:
		// LogLevel: ERROR
		// LogType: TWILIO
		return "Downstream Authentication Failed"

	case 60002:
		// LogLevel: ERROR
		// LogType: TWILIO
		return "End User Identification Timeout"

	case 60003:
		// LogLevel: ERROR
		// LogType: TWILIO
		return "End User Data is Not Available"

	case 60004:
		// LogLevel: ERROR
		// LogType: TWILIO
		return "Invalid Configuration "

	case 60005:
		// LogLevel: ERROR
		// LogType: TWILIO
		return "Downstream Carrier Error"

	case 60006:
		// LogLevel: ERROR
		// LogType: TWILIO
		return "Invalid Phone Number"

	case 60007:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Downstream Verification Failed"

	case 60008:
		// LogLevel: ERROR
		// LogType: TWILIO
		return "Unsupported Carrier"

	case 60600:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Unprovisioned or out of coverage"

	case 60601:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Authorization required for Canada lookups"

	case 60606:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Lookup Package is Not Enabled"

	case 60607:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Lookup Unsupported Country"

	case 60608:
		// LogLevel: ERROR
		// LogType: CARRIER
		return "Lookup Error"

	case 60609:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Live activity not enabled"

	case 60610:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Phone number outside of coverage"

	case 60611:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Lookup Package Quota Reached"

	case 60612:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Requested phone number not mobile"

	case 60613:
		// LogLevel: ERROR
		// LogType: CARRIER
		return "Lookup Provider Degradation"

	case 60614:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Lookup Request Must Be Completed in Different Twilio Region"

	case 60616:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Lookup rate limit exceeded"

	case 60617:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Lookup Not Enough Request Parameters"

	case 60618:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Lookup Malformed Request Parameter"

	case 60619:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Lookup Request Cannot be Completed in Twilio Region"

	case 60620:
		// LogLevel: ERROR
		// LogType: CARRIER
		return "Lookup SIM Swap Information is Incomplete From Carrier"

	case 60621:
		// LogLevel: ERROR
		// LogType: CARRIER
		return "Lookup Carrier Information Not Available"

	case 60622:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid Magic Number"

	case 60623:
		// LogLevel: WARNING
		// LogType: TWILIO
		return "Verification Not Found"

	case 60624:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Maximum rate limit for Trial Accounts"

	case 60699:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Lookup Usage Disabled"

	case 70051:
		// LogLevel: ERROR
		// LogType: TWILIO
		return "Authorization Failed"

	case 80603:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Non Unique Session Name"

	case 84001:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Workflow execution timed out."

	case 84002:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Workflow execution failed. "

	case 84003:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Unable to render block."

	case 84004:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Error while creating execution via REST API."

	case 90011:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "MessageSid is invalid"

	case 90012:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "'Recipients' list has too many items [deprecated] "

	case 90015:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Body and Template (Body, Sid, Language, Args) are provided"

	case 90025:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Template body has unsupported tag type"

	case 90026:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Template body could not be parsed"

	case 90034:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "'BroadcastStatusCallbackUrl' is too long"

	case 90038:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "'BroadcastStatusCallbackUrl' is invalid"

	case 91202:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Not Found"

	case 91203:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Method Not Allowed"

	case 94600:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Filter limit exceeded"

	case 94601:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Date range is not valid"

	case 94602:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Invalid FromDate"

	case 94603:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Ttl is out of range"

	case 94604:
		// LogLevel: ERROR
		// LogType: APPLICATION
		return "Account Sid on Legal Hold."
	default:
		return "Unknown Error"
	}
}
