# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: phonelookup

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    binary: phonelookup
    id: phonelookup
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.buildVersion={{.Version}} -X main.buildSha={{.Commit}}"

# proxies from the go mod proxy before building
# https://goreleaser.com/customization/gomod
gomod:
  proxy: true

archives:
  - formats:
      - tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ["zip"]

brews:
  - repository:
      owner: webdestroya
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_SCOOP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/webdestroya/phonelookup
    url_template: "https://github.com/webdestroya/phonelookup/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    description: "Simple utility to return caller ID info from a phone number."
    skip_upload: auto
    license: "MIT"
    commit_author:
      name: cloud87bot
      email: 114977785+cloud87bot@users.noreply.github.com
    test: |
      system "#{bin}/phonelookup --help"
    install: |
      bin.install "phonelookup"

scoops:
  - repository:
      owner: webdestroya
      name: scoop-bucket
      token: "{{ .Env.HOMEBREW_SCOOP_GITHUB_TOKEN }}"
      branch: main
    url_template: "https://github.com/webdestroya/phonelookup/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: cloud87bot
      email: 114977785+cloud87bot@users.noreply.github.com
    homepage: https://github.com/webdestroya/phonelookup
    description: "Simple utility to return caller ID info from a phone number."
    license: MIT

nfpms:
  - id: nfpm-default
    package_name: phonelookup
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Mitch Dempsey
    homepage: https://github.com/webdestroya/phonelookup
    maintainer: Mitch Dempsey <webdestroya@users.noreply.github.com>
    description: "Simple utility to return caller ID info from a phone number."
    license: MIT
    section: utils
    priority: extra
    formats:
      - deb
      - rpm
      - apk

universal_binaries:
  - id: phonelookup
    name_template: "{{ .ProjectName }}"
    replace: false


# config the checksum filename
# https://goreleaser.com/customization/checksum
checksum:
  name_template: "checksums.txt"

# create a source tarball
# https://goreleaser.com/customization/source/
source:
  enabled: true

# creates SBOMs of all archives and the source tarball using syft
# https://goreleaser.com/customization/sbom
sboms:
  - artifacts: archive
  - id: source # Two different sbom configurations need two different IDs
    artifacts: source

# signs the checksum file
# all files (including the sboms) are included in the checksum, so we don't need to sign each one if we don't want to
# https://goreleaser.com/customization/sign
signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum
    output: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# # create a docker image
# # https://goreleaser.com/customization/docker
# dockers:
#   - image_templates:
#       - "ghcr.io/webdestroya/phonelookup:{{ .Tag }}"
#     dockerfile: Dockerfile
#     build_flag_templates:
#       - "--pull"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.name={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       - "--label=org.opencontainers.image.source={{.GitURL}}"

# # signs our docker image
# # https://goreleaser.com/customization/docker_sign
# docker_signs:
#   - cmd: cosign
#     artifacts: images
#     output: true
#     args:
#       - "sign"
#       - "${artifact}"
#       - "--yes" # needed on cosign 2.0.0+