#
# Releaser workflow setup
# https://goreleaser.com/ci/actions/
#
name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access
  attestations: write # needed for provenance

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: sigstore/cosign-installer@v3.8.0 # installs cosign

      - uses: anchore/sbom-action/download-syft@v0.18.0 # installs syft

      # - uses: docker/login-action@v3 # login to ghcr
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - uses: goreleaser/goreleaser-action@v6 # run goreleaser
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_SCOOP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_SCOOP_GITHUB_TOKEN }}

      - uses: actions/attest-build-provenance@v2
        with:
          subject-checksums: ./dist/checksums.txt
